# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title  Jackknife estimator for mean and its variance
#' @description Jackknife estimator for mean and its variance using Rcpp
#' @param x a vector composed of sample points
#' @return a 2-dimension vector represent the jackknife estimate of mean and its variance
#' @examples
#' \dontrun{
#' x<-rnorm(1000,5,5)
#' jack(x)
#' }
#' @export
jack <- function(x) {
    .Call('_SC19009_jack', PACKAGE = 'SC19009', x)
}

